# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac69aa69f0d423cd11a9388c5ea2bb9c938bde3b2ae5aede5e0c05384fd345f3a0532808f67229f48322b8737f9f95e973f5d9a5180000767ba3e72a6f01b887

test:
  secret_key_base: f485bf61c6a2c52b5b604a1fe3e2a5eb28243b055c685a3bab2becb3181be039a776d4179d6a6e2997ce9b497bf62f743a37299cd04418896c28650c4aa0ab12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
